on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'

      - name: dotnet build
        run: dotnet build